export const UPDATE_VITALITY = 'UPDATE_VITALITY'
export const UPDATE_ACTION = 'UPDATE_ACTION'
export const UPDATE_MIND = 'UPDATE_MIND'

export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PLAY_MODE_CHANGED = 'PLAY_MODE_CHANGED'

export const GET_AVAILABLE_CHARACTERS_START = 'GET_AVAILABLE_CHARACTERS_START'
export const GET_AVAILABLE_CHARACTERS_SUCCESS = 'GET_AVAILABLE_CHARACTERS_SUCCESS'
export const GET_AVAILABLE_CHARACTERS_ERROR = 'GET_AVAILABLE_CHARACTERS_ERROR'

export const CREATE_CHARACTER_START = 'CREATE_CHARACTER_START'
export const CREATE_CHARACTER_SUCCESS = 'CREATE_CHARACTER_SUCCESS'
export const CREATE_CHARACTER_ERROR = 'CREATE_CHARACTER_ERROR'
