// Chat ---
export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR'

// Auth ---
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// Game State ---
export const PLAY_MODE_CHANGED = 'PLAY_MODE_CHANGED'

// Character ---
export const GET_AVAILABLE_CHARACTERS_START = 'GET_AVAILABLE_CHARACTERS_START'
export const GET_AVAILABLE_CHARACTERS_SUCCESS = 'GET_AVAILABLE_CHARACTERS_SUCCESS'
export const GET_AVAILABLE_CHARACTERS_ERROR = 'GET_AVAILABLE_CHARACTERS_ERROR'

export const SELECT_CHARACTER_START = 'SELECT_CHARACTER_START'
export const SELECT_CHARACTER_SUCCESS = 'SELECT_CHARACTER_SUCCESS'
export const SELECT_CHARACTER_ERROR = 'SELECT_CHARACTER_ERROR'

export const CREATE_CHARACTER_START = 'CREATE_CHARACTER_START'
export const CREATE_CHARACTER_SUCCESS = 'CREATE_CHARACTER_SUCCESS'
export const CREATE_CHARACTER_ERROR = 'CREATE_CHARACTER_ERROR'

export const DELETE_CHARACTER_START = 'DELETE_CHARACTER_START'
export const DELETE_CHARACTER_SUCCESS = 'DELETE_CHARACTER_SUCCESS'
export const DELETE_CHARACTER_ERROR = 'DELETE_CHARACTER_ERROR'

export const UPDATE_VITALITY = 'UPDATE_VITALITY'
export const UPDATE_ACTION = 'UPDATE_ACTION'
export const UPDATE_MIND = 'UPDATE_MIND'

// World ---
export const GET_WORLD_START = 'GET_WORLD_START'
export const GET_WORLD_SUCCESS = 'GET_WORLD_SUCCESS'
export const GET_WORLD_ERROR = 'GET_WORLD_ERROR'
