export const UPDATE_VITALITY = 'UPDATE_VITALITY'
export const UPDATE_ACTION = 'UPDATE_ACTION'
export const UPDATE_MIND = 'UPDATE_MIND'

export const GET_MESSAGES = 'GET_MESSAGES'
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PLAY_MODE_CHANGED = 'PLAY_MODE_CHANGED'

export const GET_CHARACTER_SELECTION_DATA = 'GET_CHARACTER_SELECTION_DATA'
export const FETCH_CHARACTER_SELECTION_DATA_ERROR = 'FETCH_CHARACTER_SELECTION_DATA_ERROR'

export const CHARACTER_CREATE = 'CHARACTER_CREATE'
